usecase-beta
direction LR
actor Administrateur
actor Organisateur
actor Visiteur

  system [ "Billetterie d'événements" ]

Administrateur -- Gère les événements et les catégories -- system
Organisateur -- Crée et gère ses événements -- system
Visiteur -- Consulte les événements et réserve des billets -- system
