usecase-beta
direction LR
actor Administrateur
actor Organisateur
actor Visiteur

Administrateur --> "consulter les catégories"
Administrateur --> "ajouter une catégorie"
Administrateur --> "modifier une catégorie"
Administrateur --> "supprimer une catégorie"
Administrateur --> "gérer les événements"
Administrateur --> "gérer les organisateurs"

Organisateur --> "créer un événement"
Organisateur --> "modifier son événement"
Organisateur --> "consulter ses événements"

Visiteur --> "consulter les événements"
Visiteur --> "rechercher un événement"
Visiteur --> "réserver un billet"
